ROOT=..

#CXXFLAGS+=-O3 -ffast-math -g -fstrict-aliasing -DNDEBUG -march=native -flto
CXXFLAGS+=-O2 -g 
#CXXFLAGS+=-O0 -g
LIBLOCS+=-L/usr/local/Cellar/openblas/0.2.19_1/lib

include ../Makefile.common

LDFLAGS+=-largp

